### ISSUE TITLE
Move infrastructure stuff in a bin folder

### ISSUE THREAD

**Issue by Thomah** [Thomah/boothby#12]
Let's keep the root as simple as it can be.
Just move boothby.sh and boothby.service inside a bin folder

**Comment by rjdoughty** [comment]
hello. I would like to try this issue

**Comment by Thomah** [comment]
Hi ! Thank for participating !
I leave the issue to you ;-)

**Comment by Thomah** [comment]
Done in commit 75a9ad8cd5f7991f49c72fb9f0cefbaf0259b636 on the branch "remove-libraries". Wait for merge before closing the issue.
