### ISSUE TITLE
Manage update with User Interface

### ISSUE THREAD

**Issue by Thomah** [Thomah/boothby#34]
As we cannot have access to the virtual machine anytime, it may come handy to have a menu on the config page to update the app.
On this page, we should have a field to store a commit hash. When a submit button is pressed, the app runs the following command in the boothby folder of the VM :
```
git checkout <commit_hash>
npm install
bin/boothby.sh restart
``` 

--> After a call, we did agree on an automatic deploy to the server when a push to master is done = https://gist.github.com/noelboss/3fe13927025b89757f8fb12e9066f2fa 

-----> 

Procédure : 

1) Go sur instance ec2 : 
 ```ssh -i ~/.ssh/VAL-JIMMYDO.pem ubuntu@ec2-35-180-118-248.eu-west-3.compute.amazonaws.com```

2) ON EC2 - If no project already : create empty folder
```mkdir ~/deploy_boothtby```

3) ON EC2 - create bare repository
```git init --bare ~/project.git```

4) ON EC2 - Create in ~/project.git/hooks/post-receive this script (change the TARGET and GIT_DIR VARIABLES): 

```
#!/bin/bash
set -eu

TARGET="/home/ubuntu/boothby"
GIT_DIR="/home/ubuntu/project.git"
BRANCH="master"

while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [[ $ref = refs/heads/"$BRANCH" ]];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                git --work-tree="$TARGET" --git-dir="$GIT_DIR" checkout -f
                cd /home/ubuntu/boothby
                npm install
                sudo systemctl restart boothby.service
                echo "service on server restarted"
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done
```

5) ON EC2 - Make executable the post-receive : 
```chmod +x project.hit/hooks/receive```

6) IN LOCAL - Go to local repo and add the bare repository as a remote(you can name it whatever you want (ec2, production, prod...)
```cd ~/Documents/Projets_Valeuriad/Boothby```
```git remote add production ubuntu@ec2-35-180-118-248.eu-west-3.compute.amazonaws.com:project.git```

7) Add your public ssh git key to the server 
```cat ~/.ssh/id_rsa.pub | ssh -i ~/.ssh/VAL-JIMMYDO.pem ubuntu@ec2-35-180-118-248.eu-west-3.compute.amazonaws.com "cat>> .ssh/authorized_keys"```

8) Now, you can direclty push to your new remote
```git push production master```

9) Optional, but if you don't want to do "git push origin master" AND "git push production master", you can do this : 
- add to .git/config in local repo
```
[remote "all"]
        url = https://github.com/YourGitAccount/ProjectDir.git
        url = ssh://ubuntu@your_ip_addr/home/ubuntu/projects/ProjectDir.git
```
-  then, just push to all 
`git push all master`

Biblio : 
- https://gist.github.com/noelboss/3fe13927025b89757f8fb12e9066f2fa#file-post-receive
- http://www.jeffhoefs.com/2012/09/setup-git-deploy-for-aws-ec2-ubuntu-instance/

**Comment by JimmyDore** [comment]
Seems interesting to me, could you call me tomorrow to tell me more ?
